# Generated by Django 5.1.4 on 2024-12-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_merch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Merch',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='product', max_length=50),
        ),
    ]
